#!/bin/bash
echo "Before you proceed, what is your age? :"
read AGE

if [ ${AGE} -ge 18 ];
then 
    echo "You are an adult"
else
    echo "You are underage"
fi



#-ge is the operator for greater than or equal to
